services:
  bot:
    build:
      context: .
      target: build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
      - 443:443
    command: npm run dev
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - TEST_GUILD_ID=${TEST_GUILD_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - MINECRAFT_SERVER_STATUS_API=${MINECRAFT_SERVER_STATUS_API}
      - GH_TOKEN=${GH_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
